### PR TITLE
typo

### PR DESCRIPTION
**Pull request by iamolegga**

### CODE REVIEW

**Comment by just-boris** [comment]
Thank you!

**Comment by iamolegga** [comment]
Btw, I'm confusing in selecting library for mocha, because `allure-framework` has two libs with same purposes and both with the same deps: current one: `mocha-allure-reporter` and [`allure-mocha`](https://github.com/allure-framework/allure-js/tree/master/packages/allure-mocha). Which is preferred? Could you please provide some extra info?

**Comment by just-boris** [comment]
`mocha-allure-reporter` is old and mature package.

`allure-mocha` is a full rewrite, can miss some features, but also may have some improvements (for example, Typescript types)

**Comment by iamolegga** [comment]
Thanks 👍

**Pull request merged**
